require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AcademicAndProfessionalQualificationsController do

  def mock_academic_and_professional_qualification(stubs={})
    @mock_academic_and_professional_qualification ||= mock_model(AcademicAndProfessionalQualification, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all academic_and_professional_qualifications as @academic_and_professional_qualifications" do
      AcademicAndProfessionalQualification.stub(:all) { [mock_academic_and_professional_qualification] }
      get :index
      assigns(:academic_and_professional_qualifications).should eq([mock_academic_and_professional_qualification])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_and_professional_qualification as @academic_and_professional_qualification" do
      AcademicAndProfessionalQualification.stub(:find).with("37") { mock_academic_and_professional_qualification }
      get :show, :id => "37"
      assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
    end
  end

  describe "GET new" do
    it "assigns a new academic_and_professional_qualification as @academic_and_professional_qualification" do
      AcademicAndProfessionalQualification.stub(:new) { mock_academic_and_professional_qualification }
      get :new
      assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_and_professional_qualification as @academic_and_professional_qualification" do
      AcademicAndProfessionalQualification.stub(:find).with("37") { mock_academic_and_professional_qualification }
      get :edit, :id => "37"
      assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created academic_and_professional_qualification as @academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:new).with({'these' => 'params'}) { mock_academic_and_professional_qualification(:save => true) }
        post :create, :academic_and_professional_qualification => {'these' => 'params'}
        assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
      end

      it "redirects to the created academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:new) { mock_academic_and_professional_qualification(:save => true) }
        post :create, :academic_and_professional_qualification => {}
        response.should redirect_to(academic_and_professional_qualification_url(mock_academic_and_professional_qualification))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_and_professional_qualification as @academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:new).with({'these' => 'params'}) { mock_academic_and_professional_qualification(:save => false) }
        post :create, :academic_and_professional_qualification => {'these' => 'params'}
        assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
      end

      it "re-renders the 'new' template" do
        AcademicAndProfessionalQualification.stub(:new) { mock_academic_and_professional_qualification(:save => false) }
        post :create, :academic_and_professional_qualification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:find).with("37") { mock_academic_and_professional_qualification }
        mock_academic_and_professional_qualification.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :academic_and_professional_qualification => {'these' => 'params'}
      end

      it "assigns the requested academic_and_professional_qualification as @academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:find) { mock_academic_and_professional_qualification(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
      end

      it "redirects to the academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:find) { mock_academic_and_professional_qualification(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(academic_and_professional_qualification_url(mock_academic_and_professional_qualification))
      end
    end

    describe "with invalid params" do
      it "assigns the academic_and_professional_qualification as @academic_and_professional_qualification" do
        AcademicAndProfessionalQualification.stub(:find) { mock_academic_and_professional_qualification(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:academic_and_professional_qualification).should be(mock_academic_and_professional_qualification)
      end

      it "re-renders the 'edit' template" do
        AcademicAndProfessionalQualification.stub(:find) { mock_academic_and_professional_qualification(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_and_professional_qualification" do
      AcademicAndProfessionalQualification.stub(:find).with("37") { mock_academic_and_professional_qualification }
      mock_academic_and_professional_qualification.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the academic_and_professional_qualifications list" do
      AcademicAndProfessionalQualification.stub(:find) { mock_academic_and_professional_qualification }
      delete :destroy, :id => "1"
      response.should redirect_to(academic_and_professional_qualifications_url)
    end
  end

end
