require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AcademicYearSemestersController do

  def mock_academic_year_semester(stubs={})
    @mock_academic_year_semester ||= mock_model(AcademicYearSemester, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all academic_year_semesters as @academic_year_semesters" do
      AcademicYearSemester.stub(:all) { [mock_academic_year_semester] }
      get :index
      assigns(:academic_year_semesters).should eq([mock_academic_year_semester])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_year_semester as @academic_year_semester" do
      AcademicYearSemester.stub(:find).with("37") { mock_academic_year_semester }
      get :show, :id => "37"
      assigns(:academic_year_semester).should be(mock_academic_year_semester)
    end
  end

  describe "GET new" do
    it "assigns a new academic_year_semester as @academic_year_semester" do
      AcademicYearSemester.stub(:new) { mock_academic_year_semester }
      get :new
      assigns(:academic_year_semester).should be(mock_academic_year_semester)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_year_semester as @academic_year_semester" do
      AcademicYearSemester.stub(:find).with("37") { mock_academic_year_semester }
      get :edit, :id => "37"
      assigns(:academic_year_semester).should be(mock_academic_year_semester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created academic_year_semester as @academic_year_semester" do
        AcademicYearSemester.stub(:new).with({'these' => 'params'}) { mock_academic_year_semester(:save => true) }
        post :create, :academic_year_semester => {'these' => 'params'}
        assigns(:academic_year_semester).should be(mock_academic_year_semester)
      end

      it "redirects to the created academic_year_semester" do
        AcademicYearSemester.stub(:new) { mock_academic_year_semester(:save => true) }
        post :create, :academic_year_semester => {}
        response.should redirect_to(academic_year_semester_url(mock_academic_year_semester))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_year_semester as @academic_year_semester" do
        AcademicYearSemester.stub(:new).with({'these' => 'params'}) { mock_academic_year_semester(:save => false) }
        post :create, :academic_year_semester => {'these' => 'params'}
        assigns(:academic_year_semester).should be(mock_academic_year_semester)
      end

      it "re-renders the 'new' template" do
        AcademicYearSemester.stub(:new) { mock_academic_year_semester(:save => false) }
        post :create, :academic_year_semester => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academic_year_semester" do
        AcademicYearSemester.stub(:find).with("37") { mock_academic_year_semester }
        mock_academic_year_semester.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :academic_year_semester => {'these' => 'params'}
      end

      it "assigns the requested academic_year_semester as @academic_year_semester" do
        AcademicYearSemester.stub(:find) { mock_academic_year_semester(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:academic_year_semester).should be(mock_academic_year_semester)
      end

      it "redirects to the academic_year_semester" do
        AcademicYearSemester.stub(:find) { mock_academic_year_semester(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(academic_year_semester_url(mock_academic_year_semester))
      end
    end

    describe "with invalid params" do
      it "assigns the academic_year_semester as @academic_year_semester" do
        AcademicYearSemester.stub(:find) { mock_academic_year_semester(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:academic_year_semester).should be(mock_academic_year_semester)
      end

      it "re-renders the 'edit' template" do
        AcademicYearSemester.stub(:find) { mock_academic_year_semester(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_year_semester" do
      AcademicYearSemester.stub(:find).with("37") { mock_academic_year_semester }
      mock_academic_year_semester.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the academic_year_semesters list" do
      AcademicYearSemester.stub(:find) { mock_academic_year_semester }
      delete :destroy, :id => "1"
      response.should redirect_to(academic_year_semesters_url)
    end
  end

end
