require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AcademicCalandersController do

  def mock_academic_calander(stubs={})
    @mock_academic_calander ||= mock_model(AcademicCalander, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all academic_calanders as @academic_calanders" do
      AcademicCalander.stub(:all) { [mock_academic_calander] }
      get :index
      assigns(:academic_calanders).should eq([mock_academic_calander])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_calander as @academic_calander" do
      AcademicCalander.stub(:find).with("37") { mock_academic_calander }
      get :show, :id => "37"
      assigns(:academic_calander).should be(mock_academic_calander)
    end
  end

  describe "GET new" do
    it "assigns a new academic_calander as @academic_calander" do
      AcademicCalander.stub(:new) { mock_academic_calander }
      get :new
      assigns(:academic_calander).should be(mock_academic_calander)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_calander as @academic_calander" do
      AcademicCalander.stub(:find).with("37") { mock_academic_calander }
      get :edit, :id => "37"
      assigns(:academic_calander).should be(mock_academic_calander)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created academic_calander as @academic_calander" do
        AcademicCalander.stub(:new).with({'these' => 'params'}) { mock_academic_calander(:save => true) }
        post :create, :academic_calander => {'these' => 'params'}
        assigns(:academic_calander).should be(mock_academic_calander)
      end

      it "redirects to the created academic_calander" do
        AcademicCalander.stub(:new) { mock_academic_calander(:save => true) }
        post :create, :academic_calander => {}
        response.should redirect_to(academic_calander_url(mock_academic_calander))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_calander as @academic_calander" do
        AcademicCalander.stub(:new).with({'these' => 'params'}) { mock_academic_calander(:save => false) }
        post :create, :academic_calander => {'these' => 'params'}
        assigns(:academic_calander).should be(mock_academic_calander)
      end

      it "re-renders the 'new' template" do
        AcademicCalander.stub(:new) { mock_academic_calander(:save => false) }
        post :create, :academic_calander => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academic_calander" do
        AcademicCalander.stub(:find).with("37") { mock_academic_calander }
        mock_academic_calander.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :academic_calander => {'these' => 'params'}
      end

      it "assigns the requested academic_calander as @academic_calander" do
        AcademicCalander.stub(:find) { mock_academic_calander(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:academic_calander).should be(mock_academic_calander)
      end

      it "redirects to the academic_calander" do
        AcademicCalander.stub(:find) { mock_academic_calander(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(academic_calander_url(mock_academic_calander))
      end
    end

    describe "with invalid params" do
      it "assigns the academic_calander as @academic_calander" do
        AcademicCalander.stub(:find) { mock_academic_calander(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:academic_calander).should be(mock_academic_calander)
      end

      it "re-renders the 'edit' template" do
        AcademicCalander.stub(:find) { mock_academic_calander(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_calander" do
      AcademicCalander.stub(:find).with("37") { mock_academic_calander }
      mock_academic_calander.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the academic_calanders list" do
      AcademicCalander.stub(:find) { mock_academic_calander }
      delete :destroy, :id => "1"
      response.should redirect_to(academic_calanders_url)
    end
  end

end
