require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AcademicYearsController do

  def mock_academic_year(stubs={})
    @mock_academic_year ||= mock_model(AcademicYear, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all academic_years as @academic_years" do
      AcademicYear.stub(:all) { [mock_academic_year] }
      get :index
      assigns(:academic_years).should eq([mock_academic_year])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_year as @academic_year" do
      AcademicYear.stub(:find).with("37") { mock_academic_year }
      get :show, :id => "37"
      assigns(:academic_year).should be(mock_academic_year)
    end
  end

  describe "GET new" do
    it "assigns a new academic_year as @academic_year" do
      AcademicYear.stub(:new) { mock_academic_year }
      get :new
      assigns(:academic_year).should be(mock_academic_year)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_year as @academic_year" do
      AcademicYear.stub(:find).with("37") { mock_academic_year }
      get :edit, :id => "37"
      assigns(:academic_year).should be(mock_academic_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created academic_year as @academic_year" do
        AcademicYear.stub(:new).with({'these' => 'params'}) { mock_academic_year(:save => true) }
        post :create, :academic_year => {'these' => 'params'}
        assigns(:academic_year).should be(mock_academic_year)
      end

      it "redirects to the created academic_year" do
        AcademicYear.stub(:new) { mock_academic_year(:save => true) }
        post :create, :academic_year => {}
        response.should redirect_to(academic_year_url(mock_academic_year))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_year as @academic_year" do
        AcademicYear.stub(:new).with({'these' => 'params'}) { mock_academic_year(:save => false) }
        post :create, :academic_year => {'these' => 'params'}
        assigns(:academic_year).should be(mock_academic_year)
      end

      it "re-renders the 'new' template" do
        AcademicYear.stub(:new) { mock_academic_year(:save => false) }
        post :create, :academic_year => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academic_year" do
        AcademicYear.stub(:find).with("37") { mock_academic_year }
        mock_academic_year.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :academic_year => {'these' => 'params'}
      end

      it "assigns the requested academic_year as @academic_year" do
        AcademicYear.stub(:find) { mock_academic_year(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:academic_year).should be(mock_academic_year)
      end

      it "redirects to the academic_year" do
        AcademicYear.stub(:find) { mock_academic_year(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(academic_year_url(mock_academic_year))
      end
    end

    describe "with invalid params" do
      it "assigns the academic_year as @academic_year" do
        AcademicYear.stub(:find) { mock_academic_year(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:academic_year).should be(mock_academic_year)
      end

      it "re-renders the 'edit' template" do
        AcademicYear.stub(:find) { mock_academic_year(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_year" do
      AcademicYear.stub(:find).with("37") { mock_academic_year }
      mock_academic_year.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the academic_years list" do
      AcademicYear.stub(:find) { mock_academic_year }
      delete :destroy, :id => "1"
      response.should redirect_to(academic_years_url)
    end
  end

end
