require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AgreementsController do

  def mock_agreement(stubs={})
    @mock_agreement ||= mock_model(Agreement, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all agreements as @agreements" do
      Agreement.stub(:all) { [mock_agreement] }
      get :index
      assigns(:agreements).should eq([mock_agreement])
    end
  end

  describe "GET show" do
    it "assigns the requested agreement as @agreement" do
      Agreement.stub(:find).with("37") { mock_agreement }
      get :show, :id => "37"
      assigns(:agreement).should be(mock_agreement)
    end
  end

  describe "GET new" do
    it "assigns a new agreement as @agreement" do
      Agreement.stub(:new) { mock_agreement }
      get :new
      assigns(:agreement).should be(mock_agreement)
    end
  end

  describe "GET edit" do
    it "assigns the requested agreement as @agreement" do
      Agreement.stub(:find).with("37") { mock_agreement }
      get :edit, :id => "37"
      assigns(:agreement).should be(mock_agreement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created agreement as @agreement" do
        Agreement.stub(:new).with({'these' => 'params'}) { mock_agreement(:save => true) }
        post :create, :agreement => {'these' => 'params'}
        assigns(:agreement).should be(mock_agreement)
      end

      it "redirects to the created agreement" do
        Agreement.stub(:new) { mock_agreement(:save => true) }
        post :create, :agreement => {}
        response.should redirect_to(agreement_url(mock_agreement))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agreement as @agreement" do
        Agreement.stub(:new).with({'these' => 'params'}) { mock_agreement(:save => false) }
        post :create, :agreement => {'these' => 'params'}
        assigns(:agreement).should be(mock_agreement)
      end

      it "re-renders the 'new' template" do
        Agreement.stub(:new) { mock_agreement(:save => false) }
        post :create, :agreement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agreement" do
        Agreement.stub(:find).with("37") { mock_agreement }
        mock_agreement.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :agreement => {'these' => 'params'}
      end

      it "assigns the requested agreement as @agreement" do
        Agreement.stub(:find) { mock_agreement(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:agreement).should be(mock_agreement)
      end

      it "redirects to the agreement" do
        Agreement.stub(:find) { mock_agreement(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(agreement_url(mock_agreement))
      end
    end

    describe "with invalid params" do
      it "assigns the agreement as @agreement" do
        Agreement.stub(:find) { mock_agreement(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:agreement).should be(mock_agreement)
      end

      it "re-renders the 'edit' template" do
        Agreement.stub(:find) { mock_agreement(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agreement" do
      Agreement.stub(:find).with("37") { mock_agreement }
      mock_agreement.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the agreements list" do
      Agreement.stub(:find) { mock_agreement }
      delete :destroy, :id => "1"
      response.should redirect_to(agreements_url)
    end
  end

end
