require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ApplicantsController do

  def mock_applicant(stubs={})
    @mock_applicant ||= mock_model(Applicant, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all applicants as @applicants" do
      Applicant.stub(:all) { [mock_applicant] }
      get :index
      assigns(:applicants).should eq([mock_applicant])
    end
  end

  describe "GET show" do
    it "assigns the requested applicant as @applicant" do
      Applicant.stub(:find).with("37") { mock_applicant }
      get :show, :id => "37"
      assigns(:applicant).should be(mock_applicant)
    end
  end

  describe "GET new" do
    it "assigns a new applicant as @applicant" do
      Applicant.stub(:new) { mock_applicant }
      get :new
      assigns(:applicant).should be(mock_applicant)
    end
  end

  describe "GET edit" do
    it "assigns the requested applicant as @applicant" do
      Applicant.stub(:find).with("37") { mock_applicant }
      get :edit, :id => "37"
      assigns(:applicant).should be(mock_applicant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created applicant as @applicant" do
        Applicant.stub(:new).with({'these' => 'params'}) { mock_applicant(:save => true) }
        post :create, :applicant => {'these' => 'params'}
        assigns(:applicant).should be(mock_applicant)
      end

      it "redirects to the created applicant" do
        Applicant.stub(:new) { mock_applicant(:save => true) }
        post :create, :applicant => {}
        response.should redirect_to(applicant_url(mock_applicant))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved applicant as @applicant" do
        Applicant.stub(:new).with({'these' => 'params'}) { mock_applicant(:save => false) }
        post :create, :applicant => {'these' => 'params'}
        assigns(:applicant).should be(mock_applicant)
      end

      it "re-renders the 'new' template" do
        Applicant.stub(:new) { mock_applicant(:save => false) }
        post :create, :applicant => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested applicant" do
        Applicant.stub(:find).with("37") { mock_applicant }
        mock_applicant.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :applicant => {'these' => 'params'}
      end

      it "assigns the requested applicant as @applicant" do
        Applicant.stub(:find) { mock_applicant(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:applicant).should be(mock_applicant)
      end

      it "redirects to the applicant" do
        Applicant.stub(:find) { mock_applicant(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(applicant_url(mock_applicant))
      end
    end

    describe "with invalid params" do
      it "assigns the applicant as @applicant" do
        Applicant.stub(:find) { mock_applicant(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:applicant).should be(mock_applicant)
      end

      it "re-renders the 'edit' template" do
        Applicant.stub(:find) { mock_applicant(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested applicant" do
      Applicant.stub(:find).with("37") { mock_applicant }
      mock_applicant.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the applicants list" do
      Applicant.stub(:find) { mock_applicant }
      delete :destroy, :id => "1"
      response.should redirect_to(applicants_url)
    end
  end

end
