require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CampusesController do

  def mock_campus(stubs={})
    @mock_campus ||= mock_model(Campus, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all campuses as @campuses" do
      Campus.stub(:all) { [mock_campus] }
      get :index
      assigns(:campuses).should eq([mock_campus])
    end
  end

  describe "GET show" do
    it "assigns the requested campus as @campus" do
      Campus.stub(:find).with("37") { mock_campus }
      get :show, :id => "37"
      assigns(:campus).should be(mock_campus)
    end
  end

  describe "GET new" do
    it "assigns a new campus as @campus" do
      Campus.stub(:new) { mock_campus }
      get :new
      assigns(:campus).should be(mock_campus)
    end
  end

  describe "GET edit" do
    it "assigns the requested campus as @campus" do
      Campus.stub(:find).with("37") { mock_campus }
      get :edit, :id => "37"
      assigns(:campus).should be(mock_campus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created campus as @campus" do
        Campus.stub(:new).with({'these' => 'params'}) { mock_campus(:save => true) }
        post :create, :campus => {'these' => 'params'}
        assigns(:campus).should be(mock_campus)
      end

      it "redirects to the created campus" do
        Campus.stub(:new) { mock_campus(:save => true) }
        post :create, :campus => {}
        response.should redirect_to(campus_url(mock_campus))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved campus as @campus" do
        Campus.stub(:new).with({'these' => 'params'}) { mock_campus(:save => false) }
        post :create, :campus => {'these' => 'params'}
        assigns(:campus).should be(mock_campus)
      end

      it "re-renders the 'new' template" do
        Campus.stub(:new) { mock_campus(:save => false) }
        post :create, :campus => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested campus" do
        Campus.stub(:find).with("37") { mock_campus }
        mock_campus.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :campus => {'these' => 'params'}
      end

      it "assigns the requested campus as @campus" do
        Campus.stub(:find) { mock_campus(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:campus).should be(mock_campus)
      end

      it "redirects to the campus" do
        Campus.stub(:find) { mock_campus(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(campus_url(mock_campus))
      end
    end

    describe "with invalid params" do
      it "assigns the campus as @campus" do
        Campus.stub(:find) { mock_campus(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:campus).should be(mock_campus)
      end

      it "re-renders the 'edit' template" do
        Campus.stub(:find) { mock_campus(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested campus" do
      Campus.stub(:find).with("37") { mock_campus }
      mock_campus.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the campuses list" do
      Campus.stub(:find) { mock_campus }
      delete :destroy, :id => "1"
      response.should redirect_to(campuses_url)
    end
  end

end
