require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CampusesController do

  def mock_campuse(stubs={})
    @mock_campuse ||= mock_model(Campuse, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all campuses as @campuses" do
      Campuse.stub(:all) { [mock_campuse] }
      get :index
      assigns(:campuses).should eq([mock_campuse])
    end
  end

  describe "GET show" do
    it "assigns the requested campuse as @campuse" do
      Campuse.stub(:find).with("37") { mock_campuse }
      get :show, :id => "37"
      assigns(:campuse).should be(mock_campuse)
    end
  end

  describe "GET new" do
    it "assigns a new campuse as @campuse" do
      Campuse.stub(:new) { mock_campuse }
      get :new
      assigns(:campuse).should be(mock_campuse)
    end
  end

  describe "GET edit" do
    it "assigns the requested campuse as @campuse" do
      Campuse.stub(:find).with("37") { mock_campuse }
      get :edit, :id => "37"
      assigns(:campuse).should be(mock_campuse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created campuse as @campuse" do
        Campuse.stub(:new).with({'these' => 'params'}) { mock_campuse(:save => true) }
        post :create, :campuse => {'these' => 'params'}
        assigns(:campuse).should be(mock_campuse)
      end

      it "redirects to the created campuse" do
        Campuse.stub(:new) { mock_campuse(:save => true) }
        post :create, :campuse => {}
        response.should redirect_to(campuse_url(mock_campuse))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved campuse as @campuse" do
        Campuse.stub(:new).with({'these' => 'params'}) { mock_campuse(:save => false) }
        post :create, :campuse => {'these' => 'params'}
        assigns(:campuse).should be(mock_campuse)
      end

      it "re-renders the 'new' template" do
        Campuse.stub(:new) { mock_campuse(:save => false) }
        post :create, :campuse => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested campuse" do
        Campuse.stub(:find).with("37") { mock_campuse }
        mock_campuse.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :campuse => {'these' => 'params'}
      end

      it "assigns the requested campuse as @campuse" do
        Campuse.stub(:find) { mock_campuse(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:campuse).should be(mock_campuse)
      end

      it "redirects to the campuse" do
        Campuse.stub(:find) { mock_campuse(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(campuse_url(mock_campuse))
      end
    end

    describe "with invalid params" do
      it "assigns the campuse as @campuse" do
        Campuse.stub(:find) { mock_campuse(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:campuse).should be(mock_campuse)
      end

      it "re-renders the 'edit' template" do
        Campuse.stub(:find) { mock_campuse(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested campuse" do
      Campuse.stub(:find).with("37") { mock_campuse }
      mock_campuse.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the campuses list" do
      Campuse.stub(:find) { mock_campuse }
      delete :destroy, :id => "1"
      response.should redirect_to(campuses_url)
    end
  end

end
