require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClassYearsController do

  def mock_class_year(stubs={})
    @mock_class_year ||= mock_model(ClassYear, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all class_years as @class_years" do
      ClassYear.stub(:all) { [mock_class_year] }
      get :index
      assigns(:class_years).should eq([mock_class_year])
    end
  end

  describe "GET show" do
    it "assigns the requested class_year as @class_year" do
      ClassYear.stub(:find).with("37") { mock_class_year }
      get :show, :id => "37"
      assigns(:class_year).should be(mock_class_year)
    end
  end

  describe "GET new" do
    it "assigns a new class_year as @class_year" do
      ClassYear.stub(:new) { mock_class_year }
      get :new
      assigns(:class_year).should be(mock_class_year)
    end
  end

  describe "GET edit" do
    it "assigns the requested class_year as @class_year" do
      ClassYear.stub(:find).with("37") { mock_class_year }
      get :edit, :id => "37"
      assigns(:class_year).should be(mock_class_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created class_year as @class_year" do
        ClassYear.stub(:new).with({'these' => 'params'}) { mock_class_year(:save => true) }
        post :create, :class_year => {'these' => 'params'}
        assigns(:class_year).should be(mock_class_year)
      end

      it "redirects to the created class_year" do
        ClassYear.stub(:new) { mock_class_year(:save => true) }
        post :create, :class_year => {}
        response.should redirect_to(class_year_url(mock_class_year))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved class_year as @class_year" do
        ClassYear.stub(:new).with({'these' => 'params'}) { mock_class_year(:save => false) }
        post :create, :class_year => {'these' => 'params'}
        assigns(:class_year).should be(mock_class_year)
      end

      it "re-renders the 'new' template" do
        ClassYear.stub(:new) { mock_class_year(:save => false) }
        post :create, :class_year => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested class_year" do
        ClassYear.stub(:find).with("37") { mock_class_year }
        mock_class_year.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :class_year => {'these' => 'params'}
      end

      it "assigns the requested class_year as @class_year" do
        ClassYear.stub(:find) { mock_class_year(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:class_year).should be(mock_class_year)
      end

      it "redirects to the class_year" do
        ClassYear.stub(:find) { mock_class_year(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(class_year_url(mock_class_year))
      end
    end

    describe "with invalid params" do
      it "assigns the class_year as @class_year" do
        ClassYear.stub(:find) { mock_class_year(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:class_year).should be(mock_class_year)
      end

      it "re-renders the 'edit' template" do
        ClassYear.stub(:find) { mock_class_year(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested class_year" do
      ClassYear.stub(:find).with("37") { mock_class_year }
      mock_class_year.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the class_years list" do
      ClassYear.stub(:find) { mock_class_year }
      delete :destroy, :id => "1"
      response.should redirect_to(class_years_url)
    end
  end

end
