require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CourseExemptionsController do

  def mock_course_exemption(stubs={})
    @mock_course_exemption ||= mock_model(CourseExemption, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all course_exemptions as @course_exemptions" do
      CourseExemption.stub(:all) { [mock_course_exemption] }
      get :index
      assigns(:course_exemptions).should eq([mock_course_exemption])
    end
  end

  describe "GET show" do
    it "assigns the requested course_exemption as @course_exemption" do
      CourseExemption.stub(:find).with("37") { mock_course_exemption }
      get :show, :id => "37"
      assigns(:course_exemption).should be(mock_course_exemption)
    end
  end

  describe "GET new" do
    it "assigns a new course_exemption as @course_exemption" do
      CourseExemption.stub(:new) { mock_course_exemption }
      get :new
      assigns(:course_exemption).should be(mock_course_exemption)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_exemption as @course_exemption" do
      CourseExemption.stub(:find).with("37") { mock_course_exemption }
      get :edit, :id => "37"
      assigns(:course_exemption).should be(mock_course_exemption)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created course_exemption as @course_exemption" do
        CourseExemption.stub(:new).with({'these' => 'params'}) { mock_course_exemption(:save => true) }
        post :create, :course_exemption => {'these' => 'params'}
        assigns(:course_exemption).should be(mock_course_exemption)
      end

      it "redirects to the created course_exemption" do
        CourseExemption.stub(:new) { mock_course_exemption(:save => true) }
        post :create, :course_exemption => {}
        response.should redirect_to(course_exemption_url(mock_course_exemption))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_exemption as @course_exemption" do
        CourseExemption.stub(:new).with({'these' => 'params'}) { mock_course_exemption(:save => false) }
        post :create, :course_exemption => {'these' => 'params'}
        assigns(:course_exemption).should be(mock_course_exemption)
      end

      it "re-renders the 'new' template" do
        CourseExemption.stub(:new) { mock_course_exemption(:save => false) }
        post :create, :course_exemption => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_exemption" do
        CourseExemption.stub(:find).with("37") { mock_course_exemption }
        mock_course_exemption.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :course_exemption => {'these' => 'params'}
      end

      it "assigns the requested course_exemption as @course_exemption" do
        CourseExemption.stub(:find) { mock_course_exemption(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:course_exemption).should be(mock_course_exemption)
      end

      it "redirects to the course_exemption" do
        CourseExemption.stub(:find) { mock_course_exemption(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(course_exemption_url(mock_course_exemption))
      end
    end

    describe "with invalid params" do
      it "assigns the course_exemption as @course_exemption" do
        CourseExemption.stub(:find) { mock_course_exemption(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:course_exemption).should be(mock_course_exemption)
      end

      it "re-renders the 'edit' template" do
        CourseExemption.stub(:find) { mock_course_exemption(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_exemption" do
      CourseExemption.stub(:find).with("37") { mock_course_exemption }
      mock_course_exemption.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the course_exemptions list" do
      CourseExemption.stub(:find) { mock_course_exemption }
      delete :destroy, :id => "1"
      response.should redirect_to(course_exemptions_url)
    end
  end

end
