require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CourseAssignmentsController do

  def mock_course_assignment(stubs={})
    @mock_course_assignment ||= mock_model(CourseAssignment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all course_assignments as @course_assignments" do
      CourseAssignment.stub(:all) { [mock_course_assignment] }
      get :index
      assigns(:course_assignments).should eq([mock_course_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested course_assignment as @course_assignment" do
      CourseAssignment.stub(:find).with("37") { mock_course_assignment }
      get :show, :id => "37"
      assigns(:course_assignment).should be(mock_course_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new course_assignment as @course_assignment" do
      CourseAssignment.stub(:new) { mock_course_assignment }
      get :new
      assigns(:course_assignment).should be(mock_course_assignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_assignment as @course_assignment" do
      CourseAssignment.stub(:find).with("37") { mock_course_assignment }
      get :edit, :id => "37"
      assigns(:course_assignment).should be(mock_course_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created course_assignment as @course_assignment" do
        CourseAssignment.stub(:new).with({'these' => 'params'}) { mock_course_assignment(:save => true) }
        post :create, :course_assignment => {'these' => 'params'}
        assigns(:course_assignment).should be(mock_course_assignment)
      end

      it "redirects to the created course_assignment" do
        CourseAssignment.stub(:new) { mock_course_assignment(:save => true) }
        post :create, :course_assignment => {}
        response.should redirect_to(course_assignment_url(mock_course_assignment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_assignment as @course_assignment" do
        CourseAssignment.stub(:new).with({'these' => 'params'}) { mock_course_assignment(:save => false) }
        post :create, :course_assignment => {'these' => 'params'}
        assigns(:course_assignment).should be(mock_course_assignment)
      end

      it "re-renders the 'new' template" do
        CourseAssignment.stub(:new) { mock_course_assignment(:save => false) }
        post :create, :course_assignment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_assignment" do
        CourseAssignment.stub(:find).with("37") { mock_course_assignment }
        mock_course_assignment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :course_assignment => {'these' => 'params'}
      end

      it "assigns the requested course_assignment as @course_assignment" do
        CourseAssignment.stub(:find) { mock_course_assignment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:course_assignment).should be(mock_course_assignment)
      end

      it "redirects to the course_assignment" do
        CourseAssignment.stub(:find) { mock_course_assignment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(course_assignment_url(mock_course_assignment))
      end
    end

    describe "with invalid params" do
      it "assigns the course_assignment as @course_assignment" do
        CourseAssignment.stub(:find) { mock_course_assignment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:course_assignment).should be(mock_course_assignment)
      end

      it "re-renders the 'edit' template" do
        CourseAssignment.stub(:find) { mock_course_assignment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_assignment" do
      CourseAssignment.stub(:find).with("37") { mock_course_assignment }
      mock_course_assignment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the course_assignments list" do
      CourseAssignment.stub(:find) { mock_course_assignment }
      delete :destroy, :id => "1"
      response.should redirect_to(course_assignments_url)
    end
  end

end
