require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CurriculumsController do

  def mock_curriculum(stubs={})
    @mock_curriculum ||= mock_model(Curriculum, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all curriculums as @curriculums" do
      Curriculum.stub(:all) { [mock_curriculum] }
      get :index
      assigns(:curriculums).should eq([mock_curriculum])
    end
  end

  describe "GET show" do
    it "assigns the requested curriculum as @curriculum" do
      Curriculum.stub(:find).with("37") { mock_curriculum }
      get :show, :id => "37"
      assigns(:curriculum).should be(mock_curriculum)
    end
  end

  describe "GET new" do
    it "assigns a new curriculum as @curriculum" do
      Curriculum.stub(:new) { mock_curriculum }
      get :new
      assigns(:curriculum).should be(mock_curriculum)
    end
  end

  describe "GET edit" do
    it "assigns the requested curriculum as @curriculum" do
      Curriculum.stub(:find).with("37") { mock_curriculum }
      get :edit, :id => "37"
      assigns(:curriculum).should be(mock_curriculum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created curriculum as @curriculum" do
        Curriculum.stub(:new).with({'these' => 'params'}) { mock_curriculum(:save => true) }
        post :create, :curriculum => {'these' => 'params'}
        assigns(:curriculum).should be(mock_curriculum)
      end

      it "redirects to the created curriculum" do
        Curriculum.stub(:new) { mock_curriculum(:save => true) }
        post :create, :curriculum => {}
        response.should redirect_to(curriculum_url(mock_curriculum))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curriculum as @curriculum" do
        Curriculum.stub(:new).with({'these' => 'params'}) { mock_curriculum(:save => false) }
        post :create, :curriculum => {'these' => 'params'}
        assigns(:curriculum).should be(mock_curriculum)
      end

      it "re-renders the 'new' template" do
        Curriculum.stub(:new) { mock_curriculum(:save => false) }
        post :create, :curriculum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curriculum" do
        Curriculum.stub(:find).with("37") { mock_curriculum }
        mock_curriculum.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :curriculum => {'these' => 'params'}
      end

      it "assigns the requested curriculum as @curriculum" do
        Curriculum.stub(:find) { mock_curriculum(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:curriculum).should be(mock_curriculum)
      end

      it "redirects to the curriculum" do
        Curriculum.stub(:find) { mock_curriculum(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(curriculum_url(mock_curriculum))
      end
    end

    describe "with invalid params" do
      it "assigns the curriculum as @curriculum" do
        Curriculum.stub(:find) { mock_curriculum(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:curriculum).should be(mock_curriculum)
      end

      it "re-renders the 'edit' template" do
        Curriculum.stub(:find) { mock_curriculum(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curriculum" do
      Curriculum.stub(:find).with("37") { mock_curriculum }
      mock_curriculum.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the curriculums list" do
      Curriculum.stub(:find) { mock_curriculum }
      delete :destroy, :id => "1"
      response.should redirect_to(curriculums_url)
    end
  end

end
