require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DormitoriesController do

  def mock_dormitory(stubs={})
    @mock_dormitory ||= mock_model(Dormitory, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all dormitories as @dormitories" do
      Dormitory.stub(:all) { [mock_dormitory] }
      get :index
      assigns(:dormitories).should eq([mock_dormitory])
    end
  end

  describe "GET show" do
    it "assigns the requested dormitory as @dormitory" do
      Dormitory.stub(:find).with("37") { mock_dormitory }
      get :show, :id => "37"
      assigns(:dormitory).should be(mock_dormitory)
    end
  end

  describe "GET new" do
    it "assigns a new dormitory as @dormitory" do
      Dormitory.stub(:new) { mock_dormitory }
      get :new
      assigns(:dormitory).should be(mock_dormitory)
    end
  end

  describe "GET edit" do
    it "assigns the requested dormitory as @dormitory" do
      Dormitory.stub(:find).with("37") { mock_dormitory }
      get :edit, :id => "37"
      assigns(:dormitory).should be(mock_dormitory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created dormitory as @dormitory" do
        Dormitory.stub(:new).with({'these' => 'params'}) { mock_dormitory(:save => true) }
        post :create, :dormitory => {'these' => 'params'}
        assigns(:dormitory).should be(mock_dormitory)
      end

      it "redirects to the created dormitory" do
        Dormitory.stub(:new) { mock_dormitory(:save => true) }
        post :create, :dormitory => {}
        response.should redirect_to(dormitory_url(mock_dormitory))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dormitory as @dormitory" do
        Dormitory.stub(:new).with({'these' => 'params'}) { mock_dormitory(:save => false) }
        post :create, :dormitory => {'these' => 'params'}
        assigns(:dormitory).should be(mock_dormitory)
      end

      it "re-renders the 'new' template" do
        Dormitory.stub(:new) { mock_dormitory(:save => false) }
        post :create, :dormitory => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dormitory" do
        Dormitory.stub(:find).with("37") { mock_dormitory }
        mock_dormitory.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :dormitory => {'these' => 'params'}
      end

      it "assigns the requested dormitory as @dormitory" do
        Dormitory.stub(:find) { mock_dormitory(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:dormitory).should be(mock_dormitory)
      end

      it "redirects to the dormitory" do
        Dormitory.stub(:find) { mock_dormitory(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(dormitory_url(mock_dormitory))
      end
    end

    describe "with invalid params" do
      it "assigns the dormitory as @dormitory" do
        Dormitory.stub(:find) { mock_dormitory(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:dormitory).should be(mock_dormitory)
      end

      it "re-renders the 'edit' template" do
        Dormitory.stub(:find) { mock_dormitory(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dormitory" do
      Dormitory.stub(:find).with("37") { mock_dormitory }
      mock_dormitory.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the dormitories list" do
      Dormitory.stub(:find) { mock_dormitory }
      delete :destroy, :id => "1"
      response.should redirect_to(dormitories_url)
    end
  end

end
