require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EnrollementTypesController do

  def mock_enrollement_type(stubs={})
    @mock_enrollement_type ||= mock_model(EnrollementType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all enrollement_types as @enrollement_types" do
      EnrollementType.stub(:all) { [mock_enrollement_type] }
      get :index
      assigns(:enrollement_types).should eq([mock_enrollement_type])
    end
  end

  describe "GET show" do
    it "assigns the requested enrollement_type as @enrollement_type" do
      EnrollementType.stub(:find).with("37") { mock_enrollement_type }
      get :show, :id => "37"
      assigns(:enrollement_type).should be(mock_enrollement_type)
    end
  end

  describe "GET new" do
    it "assigns a new enrollement_type as @enrollement_type" do
      EnrollementType.stub(:new) { mock_enrollement_type }
      get :new
      assigns(:enrollement_type).should be(mock_enrollement_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested enrollement_type as @enrollement_type" do
      EnrollementType.stub(:find).with("37") { mock_enrollement_type }
      get :edit, :id => "37"
      assigns(:enrollement_type).should be(mock_enrollement_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created enrollement_type as @enrollement_type" do
        EnrollementType.stub(:new).with({'these' => 'params'}) { mock_enrollement_type(:save => true) }
        post :create, :enrollement_type => {'these' => 'params'}
        assigns(:enrollement_type).should be(mock_enrollement_type)
      end

      it "redirects to the created enrollement_type" do
        EnrollementType.stub(:new) { mock_enrollement_type(:save => true) }
        post :create, :enrollement_type => {}
        response.should redirect_to(enrollement_type_url(mock_enrollement_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enrollement_type as @enrollement_type" do
        EnrollementType.stub(:new).with({'these' => 'params'}) { mock_enrollement_type(:save => false) }
        post :create, :enrollement_type => {'these' => 'params'}
        assigns(:enrollement_type).should be(mock_enrollement_type)
      end

      it "re-renders the 'new' template" do
        EnrollementType.stub(:new) { mock_enrollement_type(:save => false) }
        post :create, :enrollement_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enrollement_type" do
        EnrollementType.stub(:find).with("37") { mock_enrollement_type }
        mock_enrollement_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :enrollement_type => {'these' => 'params'}
      end

      it "assigns the requested enrollement_type as @enrollement_type" do
        EnrollementType.stub(:find) { mock_enrollement_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:enrollement_type).should be(mock_enrollement_type)
      end

      it "redirects to the enrollement_type" do
        EnrollementType.stub(:find) { mock_enrollement_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(enrollement_type_url(mock_enrollement_type))
      end
    end

    describe "with invalid params" do
      it "assigns the enrollement_type as @enrollement_type" do
        EnrollementType.stub(:find) { mock_enrollement_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:enrollement_type).should be(mock_enrollement_type)
      end

      it "re-renders the 'edit' template" do
        EnrollementType.stub(:find) { mock_enrollement_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enrollement_type" do
      EnrollementType.stub(:find).with("37") { mock_enrollement_type }
      mock_enrollement_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the enrollement_types list" do
      EnrollementType.stub(:find) { mock_enrollement_type }
      delete :destroy, :id => "1"
      response.should redirect_to(enrollement_types_url)
    end
  end

end
