require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EthnicitiesController do

  def mock_ethnicity(stubs={})
    @mock_ethnicity ||= mock_model(Ethnicity, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ethnicities as @ethnicities" do
      Ethnicity.stub(:all) { [mock_ethnicity] }
      get :index
      assigns(:ethnicities).should eq([mock_ethnicity])
    end
  end

  describe "GET show" do
    it "assigns the requested ethnicity as @ethnicity" do
      Ethnicity.stub(:find).with("37") { mock_ethnicity }
      get :show, :id => "37"
      assigns(:ethnicity).should be(mock_ethnicity)
    end
  end

  describe "GET new" do
    it "assigns a new ethnicity as @ethnicity" do
      Ethnicity.stub(:new) { mock_ethnicity }
      get :new
      assigns(:ethnicity).should be(mock_ethnicity)
    end
  end

  describe "GET edit" do
    it "assigns the requested ethnicity as @ethnicity" do
      Ethnicity.stub(:find).with("37") { mock_ethnicity }
      get :edit, :id => "37"
      assigns(:ethnicity).should be(mock_ethnicity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ethnicity as @ethnicity" do
        Ethnicity.stub(:new).with({'these' => 'params'}) { mock_ethnicity(:save => true) }
        post :create, :ethnicity => {'these' => 'params'}
        assigns(:ethnicity).should be(mock_ethnicity)
      end

      it "redirects to the created ethnicity" do
        Ethnicity.stub(:new) { mock_ethnicity(:save => true) }
        post :create, :ethnicity => {}
        response.should redirect_to(ethnicity_url(mock_ethnicity))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ethnicity as @ethnicity" do
        Ethnicity.stub(:new).with({'these' => 'params'}) { mock_ethnicity(:save => false) }
        post :create, :ethnicity => {'these' => 'params'}
        assigns(:ethnicity).should be(mock_ethnicity)
      end

      it "re-renders the 'new' template" do
        Ethnicity.stub(:new) { mock_ethnicity(:save => false) }
        post :create, :ethnicity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ethnicity" do
        Ethnicity.stub(:find).with("37") { mock_ethnicity }
        mock_ethnicity.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ethnicity => {'these' => 'params'}
      end

      it "assigns the requested ethnicity as @ethnicity" do
        Ethnicity.stub(:find) { mock_ethnicity(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ethnicity).should be(mock_ethnicity)
      end

      it "redirects to the ethnicity" do
        Ethnicity.stub(:find) { mock_ethnicity(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ethnicity_url(mock_ethnicity))
      end
    end

    describe "with invalid params" do
      it "assigns the ethnicity as @ethnicity" do
        Ethnicity.stub(:find) { mock_ethnicity(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ethnicity).should be(mock_ethnicity)
      end

      it "re-renders the 'edit' template" do
        Ethnicity.stub(:find) { mock_ethnicity(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ethnicity" do
      Ethnicity.stub(:find).with("37") { mock_ethnicity }
      mock_ethnicity.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ethnicities list" do
      Ethnicity.stub(:find) { mock_ethnicity }
      delete :destroy, :id => "1"
      response.should redirect_to(ethnicities_url)
    end
  end

end
