require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FinancialSupportsController do

  def mock_financial_support(stubs={})
    @mock_financial_support ||= mock_model(FinancialSupport, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all financial_supports as @financial_supports" do
      FinancialSupport.stub(:all) { [mock_financial_support] }
      get :index
      assigns(:financial_supports).should eq([mock_financial_support])
    end
  end

  describe "GET show" do
    it "assigns the requested financial_support as @financial_support" do
      FinancialSupport.stub(:find).with("37") { mock_financial_support }
      get :show, :id => "37"
      assigns(:financial_support).should be(mock_financial_support)
    end
  end

  describe "GET new" do
    it "assigns a new financial_support as @financial_support" do
      FinancialSupport.stub(:new) { mock_financial_support }
      get :new
      assigns(:financial_support).should be(mock_financial_support)
    end
  end

  describe "GET edit" do
    it "assigns the requested financial_support as @financial_support" do
      FinancialSupport.stub(:find).with("37") { mock_financial_support }
      get :edit, :id => "37"
      assigns(:financial_support).should be(mock_financial_support)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created financial_support as @financial_support" do
        FinancialSupport.stub(:new).with({'these' => 'params'}) { mock_financial_support(:save => true) }
        post :create, :financial_support => {'these' => 'params'}
        assigns(:financial_support).should be(mock_financial_support)
      end

      it "redirects to the created financial_support" do
        FinancialSupport.stub(:new) { mock_financial_support(:save => true) }
        post :create, :financial_support => {}
        response.should redirect_to(financial_support_url(mock_financial_support))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved financial_support as @financial_support" do
        FinancialSupport.stub(:new).with({'these' => 'params'}) { mock_financial_support(:save => false) }
        post :create, :financial_support => {'these' => 'params'}
        assigns(:financial_support).should be(mock_financial_support)
      end

      it "re-renders the 'new' template" do
        FinancialSupport.stub(:new) { mock_financial_support(:save => false) }
        post :create, :financial_support => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested financial_support" do
        FinancialSupport.stub(:find).with("37") { mock_financial_support }
        mock_financial_support.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :financial_support => {'these' => 'params'}
      end

      it "assigns the requested financial_support as @financial_support" do
        FinancialSupport.stub(:find) { mock_financial_support(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:financial_support).should be(mock_financial_support)
      end

      it "redirects to the financial_support" do
        FinancialSupport.stub(:find) { mock_financial_support(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(financial_support_url(mock_financial_support))
      end
    end

    describe "with invalid params" do
      it "assigns the financial_support as @financial_support" do
        FinancialSupport.stub(:find) { mock_financial_support(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:financial_support).should be(mock_financial_support)
      end

      it "re-renders the 'edit' template" do
        FinancialSupport.stub(:find) { mock_financial_support(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested financial_support" do
      FinancialSupport.stub(:find).with("37") { mock_financial_support }
      mock_financial_support.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the financial_supports list" do
      FinancialSupport.stub(:find) { mock_financial_support }
      delete :destroy, :id => "1"
      response.should redirect_to(financial_supports_url)
    end
  end

end
