require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NationalitiesController do

  def mock_nationality(stubs={})
    @mock_nationality ||= mock_model(Nationality, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all nationalities as @nationalities" do
      Nationality.stub(:all) { [mock_nationality] }
      get :index
      assigns(:nationalities).should eq([mock_nationality])
    end
  end

  describe "GET show" do
    it "assigns the requested nationality as @nationality" do
      Nationality.stub(:find).with("37") { mock_nationality }
      get :show, :id => "37"
      assigns(:nationality).should be(mock_nationality)
    end
  end

  describe "GET new" do
    it "assigns a new nationality as @nationality" do
      Nationality.stub(:new) { mock_nationality }
      get :new
      assigns(:nationality).should be(mock_nationality)
    end
  end

  describe "GET edit" do
    it "assigns the requested nationality as @nationality" do
      Nationality.stub(:find).with("37") { mock_nationality }
      get :edit, :id => "37"
      assigns(:nationality).should be(mock_nationality)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created nationality as @nationality" do
        Nationality.stub(:new).with({'these' => 'params'}) { mock_nationality(:save => true) }
        post :create, :nationality => {'these' => 'params'}
        assigns(:nationality).should be(mock_nationality)
      end

      it "redirects to the created nationality" do
        Nationality.stub(:new) { mock_nationality(:save => true) }
        post :create, :nationality => {}
        response.should redirect_to(nationality_url(mock_nationality))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nationality as @nationality" do
        Nationality.stub(:new).with({'these' => 'params'}) { mock_nationality(:save => false) }
        post :create, :nationality => {'these' => 'params'}
        assigns(:nationality).should be(mock_nationality)
      end

      it "re-renders the 'new' template" do
        Nationality.stub(:new) { mock_nationality(:save => false) }
        post :create, :nationality => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nationality" do
        Nationality.stub(:find).with("37") { mock_nationality }
        mock_nationality.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :nationality => {'these' => 'params'}
      end

      it "assigns the requested nationality as @nationality" do
        Nationality.stub(:find) { mock_nationality(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:nationality).should be(mock_nationality)
      end

      it "redirects to the nationality" do
        Nationality.stub(:find) { mock_nationality(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(nationality_url(mock_nationality))
      end
    end

    describe "with invalid params" do
      it "assigns the nationality as @nationality" do
        Nationality.stub(:find) { mock_nationality(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:nationality).should be(mock_nationality)
      end

      it "re-renders the 'edit' template" do
        Nationality.stub(:find) { mock_nationality(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nationality" do
      Nationality.stub(:find).with("37") { mock_nationality }
      mock_nationality.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the nationalities list" do
      Nationality.stub(:find) { mock_nationality }
      delete :destroy, :id => "1"
      response.should redirect_to(nationalities_url)
    end
  end

end
