require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OfferedCoursesController do

  def mock_offered_course(stubs={})
    @mock_offered_course ||= mock_model(OfferedCourse, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all offered_courses as @offered_courses" do
      OfferedCourse.stub(:all) { [mock_offered_course] }
      get :index
      assigns(:offered_courses).should eq([mock_offered_course])
    end
  end

  describe "GET show" do
    it "assigns the requested offered_course as @offered_course" do
      OfferedCourse.stub(:find).with("37") { mock_offered_course }
      get :show, :id => "37"
      assigns(:offered_course).should be(mock_offered_course)
    end
  end

  describe "GET new" do
    it "assigns a new offered_course as @offered_course" do
      OfferedCourse.stub(:new) { mock_offered_course }
      get :new
      assigns(:offered_course).should be(mock_offered_course)
    end
  end

  describe "GET edit" do
    it "assigns the requested offered_course as @offered_course" do
      OfferedCourse.stub(:find).with("37") { mock_offered_course }
      get :edit, :id => "37"
      assigns(:offered_course).should be(mock_offered_course)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created offered_course as @offered_course" do
        OfferedCourse.stub(:new).with({'these' => 'params'}) { mock_offered_course(:save => true) }
        post :create, :offered_course => {'these' => 'params'}
        assigns(:offered_course).should be(mock_offered_course)
      end

      it "redirects to the created offered_course" do
        OfferedCourse.stub(:new) { mock_offered_course(:save => true) }
        post :create, :offered_course => {}
        response.should redirect_to(offered_course_url(mock_offered_course))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved offered_course as @offered_course" do
        OfferedCourse.stub(:new).with({'these' => 'params'}) { mock_offered_course(:save => false) }
        post :create, :offered_course => {'these' => 'params'}
        assigns(:offered_course).should be(mock_offered_course)
      end

      it "re-renders the 'new' template" do
        OfferedCourse.stub(:new) { mock_offered_course(:save => false) }
        post :create, :offered_course => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested offered_course" do
        OfferedCourse.stub(:find).with("37") { mock_offered_course }
        mock_offered_course.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :offered_course => {'these' => 'params'}
      end

      it "assigns the requested offered_course as @offered_course" do
        OfferedCourse.stub(:find) { mock_offered_course(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:offered_course).should be(mock_offered_course)
      end

      it "redirects to the offered_course" do
        OfferedCourse.stub(:find) { mock_offered_course(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(offered_course_url(mock_offered_course))
      end
    end

    describe "with invalid params" do
      it "assigns the offered_course as @offered_course" do
        OfferedCourse.stub(:find) { mock_offered_course(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:offered_course).should be(mock_offered_course)
      end

      it "re-renders the 'edit' template" do
        OfferedCourse.stub(:find) { mock_offered_course(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested offered_course" do
      OfferedCourse.stub(:find).with("37") { mock_offered_course }
      mock_offered_course.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the offered_courses list" do
      OfferedCourse.stub(:find) { mock_offered_course }
      delete :destroy, :id => "1"
      response.should redirect_to(offered_courses_url)
    end
  end

end
