require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProgramsController do

  def mock_program(stubs={})
    @mock_program ||= mock_model(Program, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all programs as @programs" do
      Program.stub(:all) { [mock_program] }
      get :index
      assigns(:programs).should eq([mock_program])
    end
  end

  describe "GET show" do
    it "assigns the requested program as @program" do
      Program.stub(:find).with("37") { mock_program }
      get :show, :id => "37"
      assigns(:program).should be(mock_program)
    end
  end

  describe "GET new" do
    it "assigns a new program as @program" do
      Program.stub(:new) { mock_program }
      get :new
      assigns(:program).should be(mock_program)
    end
  end

  describe "GET edit" do
    it "assigns the requested program as @program" do
      Program.stub(:find).with("37") { mock_program }
      get :edit, :id => "37"
      assigns(:program).should be(mock_program)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created program as @program" do
        Program.stub(:new).with({'these' => 'params'}) { mock_program(:save => true) }
        post :create, :program => {'these' => 'params'}
        assigns(:program).should be(mock_program)
      end

      it "redirects to the created program" do
        Program.stub(:new) { mock_program(:save => true) }
        post :create, :program => {}
        response.should redirect_to(program_url(mock_program))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved program as @program" do
        Program.stub(:new).with({'these' => 'params'}) { mock_program(:save => false) }
        post :create, :program => {'these' => 'params'}
        assigns(:program).should be(mock_program)
      end

      it "re-renders the 'new' template" do
        Program.stub(:new) { mock_program(:save => false) }
        post :create, :program => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested program" do
        Program.stub(:find).with("37") { mock_program }
        mock_program.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :program => {'these' => 'params'}
      end

      it "assigns the requested program as @program" do
        Program.stub(:find) { mock_program(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:program).should be(mock_program)
      end

      it "redirects to the program" do
        Program.stub(:find) { mock_program(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(program_url(mock_program))
      end
    end

    describe "with invalid params" do
      it "assigns the program as @program" do
        Program.stub(:find) { mock_program(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:program).should be(mock_program)
      end

      it "re-renders the 'edit' template" do
        Program.stub(:find) { mock_program(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested program" do
      Program.stub(:find).with("37") { mock_program }
      mock_program.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the programs list" do
      Program.stub(:find) { mock_program }
      delete :destroy, :id => "1"
      response.should redirect_to(programs_url)
    end
  end

end
