require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RelevantPublicationsController do

  def mock_relevant_publication(stubs={})
    @mock_relevant_publication ||= mock_model(RelevantPublication, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all relevant_publications as @relevant_publications" do
      RelevantPublication.stub(:all) { [mock_relevant_publication] }
      get :index
      assigns(:relevant_publications).should eq([mock_relevant_publication])
    end
  end

  describe "GET show" do
    it "assigns the requested relevant_publication as @relevant_publication" do
      RelevantPublication.stub(:find).with("37") { mock_relevant_publication }
      get :show, :id => "37"
      assigns(:relevant_publication).should be(mock_relevant_publication)
    end
  end

  describe "GET new" do
    it "assigns a new relevant_publication as @relevant_publication" do
      RelevantPublication.stub(:new) { mock_relevant_publication }
      get :new
      assigns(:relevant_publication).should be(mock_relevant_publication)
    end
  end

  describe "GET edit" do
    it "assigns the requested relevant_publication as @relevant_publication" do
      RelevantPublication.stub(:find).with("37") { mock_relevant_publication }
      get :edit, :id => "37"
      assigns(:relevant_publication).should be(mock_relevant_publication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created relevant_publication as @relevant_publication" do
        RelevantPublication.stub(:new).with({'these' => 'params'}) { mock_relevant_publication(:save => true) }
        post :create, :relevant_publication => {'these' => 'params'}
        assigns(:relevant_publication).should be(mock_relevant_publication)
      end

      it "redirects to the created relevant_publication" do
        RelevantPublication.stub(:new) { mock_relevant_publication(:save => true) }
        post :create, :relevant_publication => {}
        response.should redirect_to(relevant_publication_url(mock_relevant_publication))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relevant_publication as @relevant_publication" do
        RelevantPublication.stub(:new).with({'these' => 'params'}) { mock_relevant_publication(:save => false) }
        post :create, :relevant_publication => {'these' => 'params'}
        assigns(:relevant_publication).should be(mock_relevant_publication)
      end

      it "re-renders the 'new' template" do
        RelevantPublication.stub(:new) { mock_relevant_publication(:save => false) }
        post :create, :relevant_publication => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relevant_publication" do
        RelevantPublication.stub(:find).with("37") { mock_relevant_publication }
        mock_relevant_publication.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :relevant_publication => {'these' => 'params'}
      end

      it "assigns the requested relevant_publication as @relevant_publication" do
        RelevantPublication.stub(:find) { mock_relevant_publication(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:relevant_publication).should be(mock_relevant_publication)
      end

      it "redirects to the relevant_publication" do
        RelevantPublication.stub(:find) { mock_relevant_publication(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(relevant_publication_url(mock_relevant_publication))
      end
    end

    describe "with invalid params" do
      it "assigns the relevant_publication as @relevant_publication" do
        RelevantPublication.stub(:find) { mock_relevant_publication(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:relevant_publication).should be(mock_relevant_publication)
      end

      it "re-renders the 'edit' template" do
        RelevantPublication.stub(:find) { mock_relevant_publication(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relevant_publication" do
      RelevantPublication.stub(:find).with("37") { mock_relevant_publication }
      mock_relevant_publication.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the relevant_publications list" do
      RelevantPublication.stub(:find) { mock_relevant_publication }
      delete :destroy, :id => "1"
      response.should redirect_to(relevant_publications_url)
    end
  end

end
