require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ServiceTypesController do

  def mock_service_type(stubs={})
    @mock_service_type ||= mock_model(ServiceType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all service_types as @service_types" do
      ServiceType.stub(:all) { [mock_service_type] }
      get :index
      assigns(:service_types).should eq([mock_service_type])
    end
  end

  describe "GET show" do
    it "assigns the requested service_type as @service_type" do
      ServiceType.stub(:find).with("37") { mock_service_type }
      get :show, :id => "37"
      assigns(:service_type).should be(mock_service_type)
    end
  end

  describe "GET new" do
    it "assigns a new service_type as @service_type" do
      ServiceType.stub(:new) { mock_service_type }
      get :new
      assigns(:service_type).should be(mock_service_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_type as @service_type" do
      ServiceType.stub(:find).with("37") { mock_service_type }
      get :edit, :id => "37"
      assigns(:service_type).should be(mock_service_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created service_type as @service_type" do
        ServiceType.stub(:new).with({'these' => 'params'}) { mock_service_type(:save => true) }
        post :create, :service_type => {'these' => 'params'}
        assigns(:service_type).should be(mock_service_type)
      end

      it "redirects to the created service_type" do
        ServiceType.stub(:new) { mock_service_type(:save => true) }
        post :create, :service_type => {}
        response.should redirect_to(service_type_url(mock_service_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_type as @service_type" do
        ServiceType.stub(:new).with({'these' => 'params'}) { mock_service_type(:save => false) }
        post :create, :service_type => {'these' => 'params'}
        assigns(:service_type).should be(mock_service_type)
      end

      it "re-renders the 'new' template" do
        ServiceType.stub(:new) { mock_service_type(:save => false) }
        post :create, :service_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_type" do
        ServiceType.stub(:find).with("37") { mock_service_type }
        mock_service_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :service_type => {'these' => 'params'}
      end

      it "assigns the requested service_type as @service_type" do
        ServiceType.stub(:find) { mock_service_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:service_type).should be(mock_service_type)
      end

      it "redirects to the service_type" do
        ServiceType.stub(:find) { mock_service_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(service_type_url(mock_service_type))
      end
    end

    describe "with invalid params" do
      it "assigns the service_type as @service_type" do
        ServiceType.stub(:find) { mock_service_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:service_type).should be(mock_service_type)
      end

      it "re-renders the 'edit' template" do
        ServiceType.stub(:find) { mock_service_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_type" do
      ServiceType.stub(:find).with("37") { mock_service_type }
      mock_service_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the service_types list" do
      ServiceType.stub(:find) { mock_service_type }
      delete :destroy, :id => "1"
      response.should redirect_to(service_types_url)
    end
  end

end
