require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ServiceAgreementsController do

  def mock_service_agreement(stubs={})
    @mock_service_agreement ||= mock_model(ServiceAgreement, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all service_agreements as @service_agreements" do
      ServiceAgreement.stub(:all) { [mock_service_agreement] }
      get :index
      assigns(:service_agreements).should eq([mock_service_agreement])
    end
  end

  describe "GET show" do
    it "assigns the requested service_agreement as @service_agreement" do
      ServiceAgreement.stub(:find).with("37") { mock_service_agreement }
      get :show, :id => "37"
      assigns(:service_agreement).should be(mock_service_agreement)
    end
  end

  describe "GET new" do
    it "assigns a new service_agreement as @service_agreement" do
      ServiceAgreement.stub(:new) { mock_service_agreement }
      get :new
      assigns(:service_agreement).should be(mock_service_agreement)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_agreement as @service_agreement" do
      ServiceAgreement.stub(:find).with("37") { mock_service_agreement }
      get :edit, :id => "37"
      assigns(:service_agreement).should be(mock_service_agreement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created service_agreement as @service_agreement" do
        ServiceAgreement.stub(:new).with({'these' => 'params'}) { mock_service_agreement(:save => true) }
        post :create, :service_agreement => {'these' => 'params'}
        assigns(:service_agreement).should be(mock_service_agreement)
      end

      it "redirects to the created service_agreement" do
        ServiceAgreement.stub(:new) { mock_service_agreement(:save => true) }
        post :create, :service_agreement => {}
        response.should redirect_to(service_agreement_url(mock_service_agreement))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_agreement as @service_agreement" do
        ServiceAgreement.stub(:new).with({'these' => 'params'}) { mock_service_agreement(:save => false) }
        post :create, :service_agreement => {'these' => 'params'}
        assigns(:service_agreement).should be(mock_service_agreement)
      end

      it "re-renders the 'new' template" do
        ServiceAgreement.stub(:new) { mock_service_agreement(:save => false) }
        post :create, :service_agreement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_agreement" do
        ServiceAgreement.stub(:find).with("37") { mock_service_agreement }
        mock_service_agreement.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :service_agreement => {'these' => 'params'}
      end

      it "assigns the requested service_agreement as @service_agreement" do
        ServiceAgreement.stub(:find) { mock_service_agreement(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:service_agreement).should be(mock_service_agreement)
      end

      it "redirects to the service_agreement" do
        ServiceAgreement.stub(:find) { mock_service_agreement(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(service_agreement_url(mock_service_agreement))
      end
    end

    describe "with invalid params" do
      it "assigns the service_agreement as @service_agreement" do
        ServiceAgreement.stub(:find) { mock_service_agreement(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:service_agreement).should be(mock_service_agreement)
      end

      it "re-renders the 'edit' template" do
        ServiceAgreement.stub(:find) { mock_service_agreement(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_agreement" do
      ServiceAgreement.stub(:find).with("37") { mock_service_agreement }
      mock_service_agreement.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the service_agreements list" do
      ServiceAgreement.stub(:find) { mock_service_agreement }
      delete :destroy, :id => "1"
      response.should redirect_to(service_agreements_url)
    end
  end

end
