require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StudentServiceStaffsController do

  def mock_student_service_staff(stubs={})
    @mock_student_service_staff ||= mock_model(StudentServiceStaff, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all student_service_staffs as @student_service_staffs" do
      StudentServiceStaff.stub(:all) { [mock_student_service_staff] }
      get :index
      assigns(:student_service_staffs).should eq([mock_student_service_staff])
    end
  end

  describe "GET show" do
    it "assigns the requested student_service_staff as @student_service_staff" do
      StudentServiceStaff.stub(:find).with("37") { mock_student_service_staff }
      get :show, :id => "37"
      assigns(:student_service_staff).should be(mock_student_service_staff)
    end
  end

  describe "GET new" do
    it "assigns a new student_service_staff as @student_service_staff" do
      StudentServiceStaff.stub(:new) { mock_student_service_staff }
      get :new
      assigns(:student_service_staff).should be(mock_student_service_staff)
    end
  end

  describe "GET edit" do
    it "assigns the requested student_service_staff as @student_service_staff" do
      StudentServiceStaff.stub(:find).with("37") { mock_student_service_staff }
      get :edit, :id => "37"
      assigns(:student_service_staff).should be(mock_student_service_staff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created student_service_staff as @student_service_staff" do
        StudentServiceStaff.stub(:new).with({'these' => 'params'}) { mock_student_service_staff(:save => true) }
        post :create, :student_service_staff => {'these' => 'params'}
        assigns(:student_service_staff).should be(mock_student_service_staff)
      end

      it "redirects to the created student_service_staff" do
        StudentServiceStaff.stub(:new) { mock_student_service_staff(:save => true) }
        post :create, :student_service_staff => {}
        response.should redirect_to(student_service_staff_url(mock_student_service_staff))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved student_service_staff as @student_service_staff" do
        StudentServiceStaff.stub(:new).with({'these' => 'params'}) { mock_student_service_staff(:save => false) }
        post :create, :student_service_staff => {'these' => 'params'}
        assigns(:student_service_staff).should be(mock_student_service_staff)
      end

      it "re-renders the 'new' template" do
        StudentServiceStaff.stub(:new) { mock_student_service_staff(:save => false) }
        post :create, :student_service_staff => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested student_service_staff" do
        StudentServiceStaff.stub(:find).with("37") { mock_student_service_staff }
        mock_student_service_staff.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :student_service_staff => {'these' => 'params'}
      end

      it "assigns the requested student_service_staff as @student_service_staff" do
        StudentServiceStaff.stub(:find) { mock_student_service_staff(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:student_service_staff).should be(mock_student_service_staff)
      end

      it "redirects to the student_service_staff" do
        StudentServiceStaff.stub(:find) { mock_student_service_staff(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(student_service_staff_url(mock_student_service_staff))
      end
    end

    describe "with invalid params" do
      it "assigns the student_service_staff as @student_service_staff" do
        StudentServiceStaff.stub(:find) { mock_student_service_staff(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:student_service_staff).should be(mock_student_service_staff)
      end

      it "re-renders the 'edit' template" do
        StudentServiceStaff.stub(:find) { mock_student_service_staff(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested student_service_staff" do
      StudentServiceStaff.stub(:find).with("37") { mock_student_service_staff }
      mock_student_service_staff.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the student_service_staffs list" do
      StudentServiceStaff.stub(:find) { mock_student_service_staff }
      delete :destroy, :id => "1"
      response.should redirect_to(student_service_staffs_url)
    end
  end

end
